version: '3.3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:3000'
    environment:
      HOST: 0.0.0.0
